##########################################
# TESTED WITH FOLLOWING PARAMETERS:
#     OS: Ubuntu 16.04 xenial
#
#     ASSUMPTIONS:
#       Ansible is installed and working
#       You are able to ssh to all hosts in inventory with ssh keys
#       You want to install on all of your hosts
#
##########################################
- name: Angular app setup playbook
  gather_facts: false
  hosts: all
  become: true
  tasks:
    
    # 1: Install docker pre-reqs (https://docs.docker.com/engine/install/ubuntu/):
    - name: install https pre-reqs using apt
      apt:
        name: "{{ item }}"
        update_cache: yes
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
    
    # 1a: Prep nodejs prereqs:
    - name: Run nodesource setup
      shell: curl -sL https://deb.nodesource.com/setup_10.x | bash -
      tags:
        - nodesource

      # 2: add dockers official GPG key:
    - name: Install GPG key for docker apt repos
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    
      # 3: add docker apt repo:
    - name: Install docker apt repo
      apt_repository:
        repo: "{{ item }}"
        state: present
      with_items:
        - deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    
      # 4: install docker engine binaries:
    - name: Install docker packages and Nodejs using apt
      apt:
        name: ['docker-ce', 'docker-ce-cli', 'containerd.io', 'nodejs']
        update_cache: yes
      tags:
        - apt_packages
  
    # 5: enable and start Docker engine    
    - name: Enable and start Docker engine services
      systemd:
        name: docker
        state: started
        enabled: yes

    # 6: prep node application
    - name: Run npm install
      shell: 
        cmd: "npm install -g @angular/cli"
        chdir: /tmp
      environment:
        PATH: "{{ ansible_env.PATH}}:/usr/local/bin:/usr/bin/"
      
    - name: create new angular application
      shell: 
        cmd: "ng new myAng-app"
        chdir: /tmp
        creates: /tmp/myAng-app/angular.json
      environment:
        PATH: "{{ ansible_env.PATH}}:/usr/local/bin:/usr/bin"

    - name: copy Dockerfile to working directory
      copy:
        src: Dockerfile
        dest: /tmp/myAng-app/Dockerfile
      tags:
        - dockerfile

    - name: Build angular app
      shell:
        cmd: "docker build -t myangularapp -t kherrmann3/myangularapp ."
        chdir: /tmp/myAng-app
      environment:
        PATH: "{{ ansible_env.PATH}}:/usr/local/bin:/usr/bin"

    - name: Run docker image
      shell:
        cmd: "docker run -d -p 4200:4200 myangularapp"
      environment:
        PATH: "{{ ansible_env.PATH}}:/usr/local/bin:/usr/bin"
---
#Dockerfile Source Code
# base image
FROM node:12

# set working directory
RUN mkdir /usr/src/app
WORKDIR /usr/src/app

# add `/usr/src/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json /usr/src/app/package.json
RUN npm install
RUN npm install -g @angular/cli@1.7.1

# add app
COPY . /usr/src/app

# start app
CMD ng serve --host 0.0.0.0